In [2]:
import numpy as np

np.__version__

'1.22.2'

In [3]:
lista1 = [1, 20, 333, 14, 19, 78, 81, 93, 76]

arr1 = np.array(lista1)

print(arr1)

arr1.shape

indice = [0, 2, 8]

arr1[indice]

[  1  20 333  14  19  78  81  93  76]


array([  1, 333,  76])

In [4]:
checagem_par = (arr1 % 2 == 0)

checagem_par

arr1[checagem_par]

array([20, 14, 78, 76])

In [5]:
arr1[0] = 11
arr1[2] = 32

arr1

array([11, 20, 32, 14, 19, 78, 81, 93, 76])

In [6]:
#arr1[0] = 'Opa, erroo'

try:
    arr1[0] = 'Opa, erroo'
except:
    print('Erro, apenas numeros')

Erro, apenas numeros


In [7]:
arr2 = np.array([12, 13, 14, 15, 16])



arr2.cumsum()
arr2.cumprod()

array([    12,    156,   2184,  32760, 524160])

In [8]:
# calculando n fatorial a partir da função abaixo usando apenas numpy:

def n_fatorial(numero):
    if numero == 0:
        return 1
    else:
        num = range(1, numero+1)
        new_list = []
        for numero in num:
            new_list.append(numero)
    
        new_array = np.array(new_list)
        cum_prod = np.cumprod(new_array)
        return cum_prod
    
n_fatorial(4)

array([ 1,  2,  6, 24])

In [9]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [10]:
arr4 = np.zeros(10)

arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
arr5 = np.eye(3)

arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
arr6 = np.diag(np.array([1, 2, 3, 10]))

arr6

array([[ 1,  0,  0,  0],
       [ 0,  2,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0,  0, 10]])

In [13]:
arr7 = np.array([[1, 2, 3], [22, 3, 10]])

arr7

array([[ 1,  2,  3],
       [22,  3, 10]])

In [14]:
arr8 = np.ones((3,3))
arr8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
listona = [[1, 2, 9], [20, 11, 98.1], [7, 8, 76]]

arr9 = np.matrix(listona, dtype = float)

print(arr9)

print(arr9[2, 2])

[[ 1.   2.   9. ]
 [20.  11.  98.1]
 [ 7.   8.  76. ]]
76.0


In [16]:
arr9.itemsize

arr9.nbytes
arr9.ndim

2

In [19]:
arr10 = np.array([17, 21, 39, 98, 82])

print(arr10.mean())

np.mean(arr10)

51.4


51.4

In [20]:
np.std(arr10)

32.76949801263364

In [25]:
arr11 = np.array([[1, 2, 3, 5], [1, 4, 9, 10]])

print(arr11)
arr11[:, 2]

[[ 1  2  3  5]
 [ 1  4  9 10]]


array([3, 9])